import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Sidebar tự sinh theo cấu trúc thư mục docs/ — mỗi chương arc42 là 1 thư mục,
 * thứ tự & nhãn do `_category_.json` quyết định. Bố cục:
 *   01..04  Bối cảnh & chiến lược
 *   05      Khối xây dựng (C4 L2/L3) — CHIA THEO TẦNG
 *   06      Runtime view — TẤT CẢ luồng LMS theo vai trò
 *   07      Triển khai — chi tiết từng container/dịch vụ (gồm Docker)
 *   08..12  Khái niệm xuyên suốt · ADR · Chất lượng · Rủi ro · Thuật ngữ
 */
const sidebars: SidebarsConfig = {
  arc42: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
